### PR TITLE
feat(legends): improve legends support

### PR DESCRIPTION
**Pull request by plouc**
- [x] add ability to handle mouseEnter/mouseLeave/click https://github.com/plouc/nivo/issues/196, https://github.com/plouc/nivo/issues/221
- [ ] add support for legends on Bubble https://github.com/plouc/nivo/issues/181
- [x] add support for legends on Waffle https://github.com/plouc/nivo/issues/226
- [x] add ability to pass custom legend data to Bar https://github.com/plouc/nivo/issues/204

### CODE REVIEW

**Comment by iohcidnal** [comment]
Thanks for the great work. This PR will really help a lot of us. When do you think we can have this? @plouc

**Comment by ArtieReus** [comment]
This PR sounds very good! It is possible to pass custom Rects, like for the bar chart passing customBar?

**Comment by plouc** [comment]
@ArtieReus, you mean custom symbols?

**Comment by ArtieReus** [comment]
@plouc yes, simbols. I need to select items from the legend to filter the chart.

**Comment by iohcidnal** [comment]
Is there any chance this will be merge?

**Comment by plouc** [comment]
@ArtieReus custom symbols have been implemented.

**Comment by wulucxy** [comment]
so，how can I test this feature。I can't still see anything changed in this PR。

**Comment by wulucxy** [comment]
hi，@plouc ， i finally manage to run this feature。but I still have problem to toggle series show/hide。
every time when I click the legend，I need to setState to remove the current series，the problem is the legend keys is also removed，because it is sync with the data。

so，what‘s your suggestion?

**Comment by plouc** [comment]
@wulu, I plan to add support for passing legend data instead of guessing it from the data itself, it should work, however I don't know when I'll be able to do so as I already have some ongoing features.

**Comment by wulucxy** [comment]
> @wulu, I plan to add support for passing legend data instead of guessing it from the data itself, it should work, however I don't know when I'll be able to do so as I already have some ongoing features.

it seems interesting。how about create a demo，and i am willing to take it to action?

**Comment by J1marotta** [comment]
Will this PR contain any documentation for the Effects part of the legends? it seems to be missing from the Api docs. 

would greatly appreciate it.

**Comment by lourenci** [comment]
Will this PR expose some way to rendering the legends outside of the component? That would solve those #274, #253 issues.

In the chart below, I can't fit the legends in it. There are a lot of legends with big words. My solution for now is disable the legends in it.

image

Thanks for the library.

**Comment by plouc** [comment]
I've kept this PR to be able to pick features from it, however it won't be merged.
@lourenci it doesn't include this feature but I'd like to add it to the lib, but I've no idea of when, it depends on the time I can spend on the project which is very limited for now.

**Comment by martin-kieliszek** [comment]
I'm excited for this change to be available

**Comment by plxel** [comment]
how is it going?

**Comment by plxel** [comment]
Maybe you can add prop for custom legend and just pass all props you pass now into your legend to this custom render prop
And then anybody can implement any legend they want

**Comment by dkim-thomas** [comment]
Is there a custom way to edit the legend for the pie chart as well? @plouc

**Comment by sattuchin** [comment]
This feature would be very useful. Please prioritize when possible. Thank you!

**Comment by marcelojrfarias** [comment]
Watching ;)

**Comment by Lisakirj** [comment]
Would be nice to have possibility to add another dataFrom for barChart legend

**Pull request closed without merging**
