### PR TITLE
feat(calendar): add TimeRange component and storybook

### PR DESCRIPTION
**Pull request by scherler**
Re-write of  #1481,  adding new logic instead of changing the old one.  

image

Forked calendar preview package:

```
"@cloudbees/nivo-calendar": "0.69.4",
```

### CODE REVIEW

**Comment by scherler** [comment]
@wyze can you comment on what is missing to make it into this repository?

**Comment by wyze** [comment]
I'll review this soon and we can make it into v0.71.

**Comment by scherler** [comment]
TIA

**Comment by anton-johansson** [comment]
Any plans for a new release soon, to get this out?

**Comment by wyze** [comment]
Next week after I am home from vacation.

**Comment by anton-johansson** [comment]
Nice! I'm having some difficulties getting the month legends to show up. I can see them in the DOM, with the correct month name, with a black font color on white background, but they just aren't visible. Any ideas?

**Pull request merged**
