### PR TITLE
Custom tooltips on ScatterPlot + optionally pass a function to the 'symbolSize' prop

### PR DESCRIPTION
**Pull request by mjsarfatti**
First of all, sorry if I post two improvements in one pull request, it's the first time I do this. Let me know if you prefer it done in some other ways.

**Improvement 1** adds custom tooltips to ScatterPlot (I basically followed what had been done in the Bar component).
I added them to the SVG component, but not to the canvas one. That's something that might have to be done before merging? Let me know your thoughts.

**Improvement 2** allows the passing of a function to 'symbolSize'. This is something that's often useful with scatter plots because it allows representing a third dimension.
I've touched @nivo/core, so I would feel better if you reviewed it. I'm not 100% sure of what I've done :)

For neither of them I've written tests. But you can see from the two added stories ('symbol size function' and 'custom tooltip') that they work.
But again, let me know if you'd prefer to have some tests (and any guidance on that would be super appreciated).

Manuele

### CODE REVIEW

**Comment by plouc** [comment]
@mjsarfatti the build fails because I think you used a newer version of prettier, maybe you're using `npm` and the repo only contains `yarn.lock` file

**Comment by plouc** [comment]
would you mind trying to install deps using yarn and re-formatting? It adds a little bit of noise to the PR.

**Comment by mjsarfatti** [comment]
So I deleted the ./node_moduels folder, then _$ yarn_ and _$ make fmt_ and it seems to have done the trick.

**Comment by plouc** [comment]
@mjsarfatti, SVG support can be added later, SVG is far more used than canvas for now :)
For tests, I need to add some basic ones on all packages and add some guidance in the contribution guide.
👍 for added stories

**Comment by plouc** [comment]
I've added the ability to use custom tooltip from the website demo, in the "interactivity" pane.

**Pull request merged**
