### PR TITLE
SwarmPlot & Scales & Annotations TypeScript migration

### LINKED ISSUE #688: Bug: Tooltip does not update for SwarmPlot
Hi, 

if a dynamic tooltip is passed to the SwarmPlot component, the tooltip is not updated. It does work for other components (e.g. Bar)

See the following demo on codesandbox: https://codesandbox.io/s/nivo-basic-demo-mcf9u

When the "Toggle Tooltip" Button is clicked, the bar chart displays "2nd Tooltip" but the SwarmPlot keeps displaying the tooltip that was initially passed to the component (saying "Tooltip") so the component did not update.

Thank you. Let me know if I can help fixing the bug.

### LINKED ISSUE #1216: Migrate @nivo/annotations to TypeScript

### LINKED ISSUE #1241: Migrate @nivo/swarmplot to TypeScript

### LINKED ISSUE #1243: Migrate @nivo/scales to TypeScript

### PR DESCRIPTION
**Pull request by plouc**
⚠️ **Depends on https://github.com/plouc/nivo/pull/1364** ⚠️

Close #688 
Close #1216 
Close #1241 
Close #1243

### CODE REVIEW

**Comment by wyze** [comment]
@plouc This is rebased to latest master. I've messed with trying to get it to build but unable to get `scales` to compile yet. I think that is why you had this in a draft state.

**Review by wyze — APPROVED** [review]

**Comment by wyze** [comment]
@plouc This should be ready to go now. I took over halfway, but since you started the PR, I can't actually add you as a reviewer. If you could take some time in the next couple of days to review and add comment(s), that would be great!

**Comment by plouc** [comment]
@wyze thank you for taking over! And sorry for the lack of reply.
Really nice to have this converted!

**Comment by wyze** [comment]
@plouc, no problem! I agree that it's time this was converted and merged. :)

**Pull request merged**
