### PR TITLE
Fix missing tooltip breaking interactivity on bar chart doc

### PR DESCRIPTION
**Pull request by publicJorn**
Fix for: https://github.com/plouc/nivo/issues/1624

### CODE REVIEW

**Comment by plouc** [comment]
@publicJorn, thank you for spotting this issue and proposing a fix! I think this now breaks the custom tooltip example.

**Comment by wyze** [comment]
Like plouc mentioned, this does break the custom tooltip example. I went ahead and created the fix in #1627 and deployed it. The website code can be quite confusing on it's setup when trying to make changes.

**Comment by jorn-cloudnatix** [comment]
Ah, the proper fix was a bit deeper down the rabbit hole. Thanks for the quick response guys!

**Comment by publicJorn** [comment]
Ah, the proper fix was a bit deeper down the rabbit hole. Thanks for the quick response guys!

**Pull request closed without merging**
