### PR TITLE
fix(types): improve typings for onMouseLeave/Enter in Bar/Pie

### PR DESCRIPTION
**Pull request by mathieumg**
Supersedes https://github.com/plouc/nivo/pull/868, covers for some of https://github.com/plouc/nivo/pull/280 (Bar & Pie, not ScatterPlot)

### CODE REVIEW

**Comment by ebwittenberg** [comment]
Has this fix been deployed? I'm running version 0.61.1 but don't see these type changes

**Comment by wyze** [comment]
@ebwittenberg These fixes would be in v0.62.0.

**Comment by ebwittenberg** [comment]
@wyze is that out yet?

**Comment by ebwittenberg** [comment]
@wyze thank you!

**Pull request merged**
