### PR TITLE
Allow custom legendNode for markers

### PR DESCRIPTION
**Pull request by Bigood**
Allow `legendNode` props on markers for finer control over legend. 

## Usecases : 

- Display other content than text (image, shape…)
- Create tooltips to display additional information, when a lot of markers are rendered and remaining place is low

## Usage :
```js
...
markers={[{
    axis: "x",
    lineStyle: {
        stroke: "lightblue",
        strokeWidth: 5
    },
    legendPosition: "top",
    legendNode: <foreignObject x={0} y={0} width={32} height={32}>
                    <FontAwesomeIcon icon={faRocket} />
                </foreignObject>,
}]}
```

## Expected result :
image

## Codechanges :

Two lines changed to bypass legendNode creation with legend text. 
Doesn't break any existing functionality, and seams easy to maintain across updates.

### CODE REVIEW

**Comment by Nikholau** [comment]
lets aprovve this PR @plouc !

**Comment by Bigood** [comment]
Up'ing this, how can I help?

**Comment by Bigood** [comment]
Right on time, as requested here is a test on Line on updated codebase. I don't know what to do to solve Vercel's deploy failure though.

Is that ok?

**Comment by Bigood** [comment]
@plouc I don't mean to be pushy, but I have a time window to edit this PR if there's something to be done. Otherwise, if everything's mergeable, could you give an estimation of when you'd have time to push the button ?

I'd personally like to upgrade my version of nivo on my project, but I can't for the moment as I heavily depend on this functionality (I dangerously use the package build by codesandbox, and can't yet find a way to use patch-package properly to patch the builded version easily).

**Comment by plouc** [comment]
> @plouc Right on time, as requested here is a test on Line on updated codebase. I don't know what to do to solve Vercel's deploy failure though.
> 
> Is that ok?

Vercel ran fine, for codesandbox, it's unrelated.

**Comment by plouc** [comment]
@Bigood, could you please run prettier?

**Pull request merged**
