### PR TITLE
feat(axes): add onClick handler to axis ticks

### PR DESCRIPTION
**Pull request by martingordon**
I found this useful in heat maps to allow for additional interactivity (for example, to allow sorting by a row/column label).

### CODE REVIEW

**Comment by martingordon** [comment]
@plouc I fixed the failing tests. Any chance we can get this merged in soon? Please let me know if there are any other changes you want me to make.

**Comment by plouc** [comment]
@martingordon, seems OK, thank you. However I think it's useful to also pass event with value, it can be used to determine click position for example, or prevent bubbling in case we a have a click handler higher in the tree.

**Comment by martingordon** [comment]
@plouc Good idea, I just pushed an update.

**Comment by debovis** [comment]
@martingordon @plouc Can someone update the documentation to reflect this? Thanks

**Pull request merged**
