### PR TITLE
chore/bump d3 interpolate and scale-chromatic

### PR DESCRIPTION
**Pull request by ollwenjones**
These both upgrade w/o breaking changes, (I checked changelogs and saw only new features and bug fixes), and both drag in the vulnerable version of d3-color when not upgraded, at least for package managers like pnpm that isolate modules w/o deduping them.

### CODE REVIEW

**Comment by ollwenjones** [comment]
seems we are on different versions of pnpm w/ slightly different lockfile versions, and this wanted to drag with it a number of minor updates to a number of things. Perhaps the pnpm lockfile needs to be handled differently?

I have pnpm version 7.18.1, locally. Can chat with other devs in the org about upgrading, probably, if we are behind (I know they are up to 8.something.)

**Comment by ericMarkunasApollo** [comment]
What's the status of this? This package now causes vulnerability warnings: https://github.com/advisories/GHSA-36jr-mh4h-2g58

**Comment by msheahen** [comment]
I'd also like to hear the status on this, would LOVE to have this vulnerability squashed

**Comment by ollwenjones** [comment]
I need help on correct node + pnpm versions for updating pnpm-lock.yaml. Otherwise it just needs approval from a maintainer.

**Comment by ericMarkunasApollo** [comment]
> I need help on correct node + pnpm versions for updating pnpm-lock.yaml. Otherwise it just needs approval from a maintainer.

@plouc Any help on this would be appreciated for @ollwenjones question :)

**Comment by plouc** [comment]
@ollwenjones, sorry for the late reply and thank you for checking the changelogs 🙏🏻 I've created [a new PR for this](https://github.com/plouc/nivo/pull/2461).

**Pull request closed without merging**
