### PR TITLE
feat(radar): orientation of radar chart

### PR DESCRIPTION
**Pull request by tkonopka**
Addresses #1898

Provides a prop `angle` that sets the global orientation for the radar chart.

Example of a default radar chart (left, `angle=0`) and a rotated chart (right, `angle=36`):

2022-04-30-radar-angle

### CODE REVIEW

**Comment by plouc** [comment]
I think we could name the property `rotation` instead what do you think? Also it would be nice to ad a test for this new feature if possible.

**Comment by tkonopka** [comment]
Thanks for the feedback @plouc. Just added some changes:

- renamed the new prop from 'angle' to 'rotation'
- added a simple unit test for the rotation feature
- prettified some code in the 'line' package (unrelated to this PR, but required for the CI)

**Review by plouc — APPROVED** [review]
LGTM

**Comment by plouc** [comment]
Thank you @tkonopka! I created [a task](https://github.com/plouc/nivo/issues/1995) to add it to the interactive demo.

**Pull request merged**
