### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by vianneyguesdon**
add keywords to be able to find Nivo via npm search bar.

### CODE REVIEW

**Comment by coooraph** [comment]
Thank you for this @vianneyguesdon, however now this file is only used to install infrastructure dependencies, the `nivo` package is deprecated and scoped packages (like `@nivo/treemap`) should be used instead

**Comment by coooraph** [comment]
It's now [private](https://github.com/plouc/nivo/blob/master/package.json#L4)

**Comment by vianneyguesdon** [comment]
Understood. I should be delete or hidden to avoid mistakes imo !
https://www.npmjs.com/package/nivo still accessible

**Comment by plouc** [comment]
@vianneyguesdon, 361 repos apparently have it as a dependency, I don't want to break those, people can still use the old one.

**Pull request closed without merging**
