### PR TITLE
Modifying Radar's Axis to be drawn by Axis.domain.line of the Theme

### PR DESCRIPTION
**Pull request by GoodGoodJM**
It seems that Radar's Axis is not currently being drawn by referring to the theme incorrectly.
Modify to draw axis using `theme.axis.domain.line`.

### CODE REVIEW

**Comment by plouc** [comment]
@GoodGoodJM, that's expected, this is the equivalent of the cartesian grid, not an axis.

**Comment by plouc** [comment]
But there's a bug in the current implementation, should be `theme.grid.line`.

**Comment by GoodGoodJM** [comment]
ok but, if use theme.gird.line, it change all line's styles of radar. If we does not want axis, all line will remove..

**Comment by plouc** [comment]
@GoodGoodJM, yes, both are part of the grid, it's the same behavior as other charts, using axis is not correct. We could add another option to disable those.

**Review by plouc — APPROVED** [review]
LGTM

**Comment by plouc** [comment]
Thank you for this fix @GoodGoodJM!

**Pull request merged**
