### PR TITLE
Adds lodash-es as a dependency to each graph's package.json

### PR DESCRIPTION
**Pull request by tpyoung**
Fixes issue #114
created by szymonmal

### CODE REVIEW

**Comment by dennyluan** [comment]
ping pong, looks like this would fix https://github.com/plouc/nivo/issues/114?

**Comment by tpyoung** [comment]
Worked for me after I added them individually.

**Comment by plouc** [comment]
Sorry for the laaaaaaate review :/ I moved to rollup and fixed lodash deps (https://github.com/plouc/nivo/pull/191).

**Comment by plouc** [comment]
It's available from `0.35.2` packages

**Pull request closed without merging**
