### PR TITLE
feat(bump): add support for defs/fill properties to AreaBump

### PR DESCRIPTION
**Pull request by recurser**
Screen Shot 2020-04-17 at 14 54 10

### CODE REVIEW

**Comment by recurser** [comment]
@plouc I couldn't get the test suite to run because I got a lot of these ` TypeError: Cannot read property 'current' of undefined
`:

```
 FAIL  packages/bar/tests/Bar.test.js (5.135s)
  ● should render a basic bar chart

    TypeError: Cannot read property 'current' of undefined

      14 |
      15 | it('should render a basic bar chart', () => {
    > 16 |     const component = renderer.create(
         |                                ^
      17 |         <Bar
      18 |             width={500}
      19 |             height={300}

      at warnIfNotScopedWithMatchingAct (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13713:31)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14706:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15455:5)
      at Object.<anonymous> (packages/bar/tests/Bar.test.js:16:32)
```

... any advice how to resolve that?

**Comment by recurser** [comment]
I'm also getting an error `Your lockfile needs to be updated, but yarn was run with --frozen-lockfile` on [Travis](https://travis-ci.org/github/plouc/nivo/builds/676062743) that I'm not sure how to resolve - I haven't touched anything yarn-related afaik.

**Comment by wyze** [comment]
Hi Dave, thanks for this! Looks really great. I have not seen that error and the tests run fine for me (`make test`). What about deleting node_modules and reinstalling?

**Comment by recurser** [comment]
Hi @wyze - all the tests pass after re-installing `node_modules` 👍 I'm not sure what happened there, but all looks good now.

**Comment by plouc** [comment]
It has been released in `v0.62.0`, thank you very much for this feature @recurser! And it's really nice to have included it on the website :)

**Pull request merged**
