### PR TITLE
Provide theme to renderTick function

### LINKED ISSUE #579: [Storybook] Bar Custom Axis Ticks doesn't work
**Describe/explain the bug**
Hey, I've just noticed that one of your storybook stories throws an exception.

**To Reproduce**
1. Go to Storybook
2. Expand `Bar`
3. Click on `custom axis ticks`

See url: https://nivo.rocks/storybook/?path=/story/bar--custom-axis-ticks

**Expected behavior**
No error 🤷‍♂ 

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 
 - Version (74.0.3729.169 (Official Build) (64-bit))

### PR DESCRIPTION
**Pull request by wyze**
Close #579

### CODE REVIEW

**Comment by plouc** [comment]
@wyze, in fact you do not need to pass down the theme property, you can use the dedicated hook to access the theme, `import { useTheme } from '@nivo/core` and then `const theme = useTheme()`.

**Comment by wyze** [comment]
The bug is the `renderTick` function doesn't receive a `theme` property. The `Axis` component already is using the `useTheme` hook, so it will provide that to the `renderTick` function, which defaults to `AxisTick`, when it isn't provided by the user.

**Comment by plouc** [comment]
You should use `useTheme` in the `renderTick` function.

**Comment by wyze** [comment]
So, you're saying to revert the above, and change the story here https://github.com/plouc/nivo/blob/0a90609bd4c7f9fb29cd95b4879a857736dbb680/packages/bar/stories/bar.stories.js#L205 to import the `useTheme` hook and use that?

**Comment by plouc** [comment]
@wyze, yes, that's the correct approach, however I've just realized that `renderTick` isn't treated as a React component, I'm currently fixing this.

**Comment by plouc** [comment]
I've created a PR => https://github.com/plouc/nivo/pull/635

**Pull request closed without merging**
