### PR TITLE
keep the tooltip inbounds

### PR DESCRIPTION
**Pull request by humanchimp**
Related to #580

Hello. Thanks for your hard work and great skill writing this library! 🙇 

This PR may not be good enough to merge, but I wanted to propose it anyway, given [this comment](https://github.com/plouc/nivo/issues/617#issuecomment-508116675), which suggests that this change (or something like it) could be appropriate. This seems hack-y to me, but I've been using this patch in my own application, and I thought it would be worth sharing. Opening this PR seemed like a good way to share this, even if the PR itself is not mergeable.

### CODE REVIEW

**Comment by vintg** [comment]
^

**Comment by shihlinlu** [comment]
Is anyone able to review this PR? I'm working on a collection of charts right now that would help resolve the tooltip positioning issue as described in #580.

**Comment by nghieptiki** [comment]
^

**Comment by vintg** [comment]
^

**Comment by vintg** [comment]
^

**Comment by vintg** [comment]
if anyone wants to make this an optional prop *
otherwise, I've been using this modification without issues so far

**Comment by shihlinlu** [comment]
Thanks @vintg for the updates! When do you expect for this PR to be merged?

**Comment by vintg** [comment]
> Thanks @vintg for the updates! When do you expect for this PR to be merged?

I don't have write access

**Comment by siemvaessen** [comment]
Hi, when will the PR be done? What is the hold-up?

**Comment by shihlinlu** [comment]
@vintg Do you know when someone with write-access will be able to merge it?

**Comment by novito** [comment]
@plouc firstly, thanks a lot for all the work you have done at Nivo. It's a great library. Is there a way we can merge this? Seems to be solving the tooltip getting out of viewport issue.

**Comment by SenelithPerera** [comment]
Any clue about when this will get merged cause I'm really in need of this in my project at work.

**Comment by plouc** [comment]
Sorry for the long delay, and thank you @humanchimp, I'll probably try to improve the tooltip behaviour at some point, but it seems that this will help a lot of people!

**Comment by novito** [comment]
thank you @plouc!

**Comment by SenelithPerera** [comment]
Hi @plouc thanks for merging the pr. Will this be published to npm anytime soon ?

**Comment by taschetto** [comment]
Dear @plouc, I don't mean to put you under pressure but would you kindly publish this on npm? It will be much appreciated. :)

**Comment by Jaquin92** [comment]
@plouc would be sick to get this published!!!!

**Comment by brycedewitt** [comment]
Just another check in - was this fix published to npm?

**Comment by wyze** [comment]
@brycedewitt Yes, it is in v0.60 and above.

**Pull request merged**
