### PR TITLE
[add_typescript_to_calendar] enable type generation

### PR DESCRIPTION
**Pull request by scherler**

### CODE REVIEW

**Comment by scherler** [comment]
@wyze can you comment on what is missing to make it into this repository?

**Comment by wyze** [comment]
Is there a reason this is needed? We have only had tsconfig files for when we convert the package to Typescript.

**Comment by scherler** [comment]
It triggers the generation of the types https://github.com/plouc/nivo/blob/93943b88e601e0e612b187a0bfbb6e6c3748597d/Makefile#L164 so when you have a type based project you can use the lib with type support.

**Comment by wyze** [comment]
This was included with #1503.

**Pull request closed without merging**
