### PR TITLE
Shows labels when bar height/width is zero

### PR DESCRIPTION
**Pull request by meganhng**
Fixes: #448 

The bar values with no height wouldn't have their labels displayed because the data wouldn't be pushed onto the graph.

### CODE REVIEW

**Comment by cazroam** [comment]
+1

**Comment by Stephen-ONeil** [comment]
+1

**Comment by ktw1016** [comment]
@plouc any chance for this to get merged in?

**Comment by Mihier-Roy** [comment]
Is there an update on when this will be released?

**Comment by justinro-underscore** [comment]
Any updates on this?

**Pull request closed without merging**
