### PR TITLE
Make line areas stack in front of each other visibly.

### PR DESCRIPTION
**Pull request by niharikasingh**
Fixing stacked area graphs as discussed in issue #150

### CODE REVIEW

**Comment by wyze** [comment]
Hey @plouc, anything we can do to help this along?

**Comment by plouc** [comment]
@niharikasingh, @wyze sorry for the late review, I don't have time for my side projects for now.

**Comment by wyze** [comment]
I totally understand how that is and go through that myself. Thank you for merging this, and the library as a whole!

**Comment by bchociej** [comment]
Hi @plouc, would you be able to make a minor release / npm version encompassing this change? Additionally, if you are open to it, some members of my team (@wyze, @niharikasingh, @steevsachs, and myself) would be interested in helping maintain nivo (review PRs, make releases, etc.) if it would be seen as a help!

**Pull request merged**
