### PR TITLE
Add forceActiveId prop for Pie

### PR DESCRIPTION
**Pull request by theomessin**
See https://github.com/plouc/nivo/issues/2059

### CODE REVIEW

**Comment by antonmelbardis** [comment]
can this please get merged?

**Comment by robertsargent** [comment]
+1 for getting this merged please

**Comment by theomessin** [comment]
@antonmelbardis @robertsargent until this is merged:
https://github.com/plouc/nivo/issues/2059#issuecomment-1287149170

**Comment by theomessin** [comment]
bump

**Comment by theomessin** [comment]
Bumpity Bump Bump

**Comment by robertsargent** [comment]
Please can this PR be reopened

**Comment by plouc** [comment]
@robertsargent, it has already been implemented in https://github.com/plouc/nivo/pull/2465, and released.

**Pull request closed without merging**
