### PR TITLE
Legend theme fill color always being overwritten

### PR DESCRIPTION
**Pull request by jefferymills**
The `textColor` prop has a default value of black which means the `fill` in the style property was always overwriting the `fill` property coming from the theme.

### CODE REVIEW

**Comment by wyze** [comment]
@plouc What value should take priority here, the theme fill color or the defaultProp from the legend item?

Also, @jefferymills, looks like there are a few tests that broke with your change.

**Comment by jefferymills** [comment]
Thanks @wyze, I wasn't able to get things running locally because the `make init` fails so I haven't been able to see why my change breaks those tests. I made the change directly in GitHub. Should I just make an issue? Basically, right now updating the legend text color with the theme isn't working.

**Comment by plouc** [comment]
@jefferymills, how does `make init` fails?

**Comment by jefferymills** [comment]
@plouc Sorry for the delay. I've been out of town. I will share the output I get when running `make init`. I'm sure it's something wrong with my setup but I'm not as experienced with build systems and most the output is over my head :)

https://docs.google.com/document/d/1d9AmyO81RTWGtdKcbzJTO63Hy2_lZ-dmKISfzOunW3Q/edit?usp=sharing

**Comment by plouc** [comment]
This issue has been fixed in master and the fix will be available soon in the upcoming release, I'm very sorry for the late reply and thank you for your contribution!

**Pull request closed without merging**
