### PR TITLE
PieLegend label fix

### PR DESCRIPTION
**Pull request by cerber717**
This is a fix for the issue 
https://github.com/plouc/nivo/issues/794

### CODE REVIEW

**Comment by le0nik** [comment]
@wyze looks like it is in fact required https://github.com/plouc/nivo/issues/808 but it doesn't look like it should be.

**Comment by plouc** [comment]
PropTypes define constrains for both internal and external API, while typings only define external/public API

**Comment by cerber717** [comment]
I am gonna add the fall back for.

**Comment by wyze** [comment]
Thanks for this @cerber717, but I went ahead and fixed this and something else in #967.

**Pull request closed without merging**
