### PR TITLE
Don't round a bar scale

### PR DESCRIPTION
**Pull request by constgen**
Fixes https://github.com/plouc/nivo/issues/840

### CODE REVIEW

**Comment by constgen** [comment]
Snapshots tests failed. Please, help me to update them if you think that this PR doesn't brake anything.

**Comment by constgen** [comment]
bump

**Comment by wyze** [comment]
@plouc Was there a specific reason to use rounded values for the index scale? Is this change going to be okay, or should we look into making some prop like `indexScale={{ round: false }}` that users can opt into?

**Comment by constgen** [comment]
Because rounding is **disabled** for all other charts. More details in the referred issue.

**Comment by plouc** [comment]
@wyze, @constgen I remember adding it for a specific use case I had, should maybe not be the default, but I think we should keep the option.

**Comment by constgen** [comment]
Do you expect it to brake something?

**Comment by wyze** [comment]
This was added in #1282. You can use `indexScale={{ type: 'band', round: false }}`. This will be available in the next version.

**Comment by wyze** [comment]
Thanks for the contribution, and sorry it didn't work out landing it this way.

**Comment by constgen** [comment]
The new option may help

**Pull request closed without merging**
