### PR TITLE
feat(swarmplot): add time scale support

### LINKED ISSUE #1120: The swarm plot breaks with time scale for values.
**Describe/explain the bug**
The swarm plot breaks with time scale for values. 

**To Reproduce**
I have created an example sandbox using Nivo swarm plot and time scale for values.
https://codesandbox.io/s/nivo-swarmplot-test-9x888

**Expected behavior**
The plot should not break and must plot as per the needed timescale.

**Screenshots**
https://codesandbox.io/s/nivo-swarmplot-test-9x888

### PR DESCRIPTION
**Pull request by SachinVarghese**
Fixes #1120 

Changes made in this PR,

- [x] Exporting timeHelpers from Nivo scales package
- [x] Supporting time scale for values in swarm plot
- [x] Adding swarm plot story for time scale example

### CODE REVIEW

**Comment by SachinVarghese** [comment]
Hi, @plouc @wyze I have managed to submit a PR for the issue I posted on discord. This also includes a new story to the swarm plot as an example. It would be great if you guys could review it soon. Thanks

**Review by wyze — APPROVED** [review]
This looks great, thank you!

**Comment by SachinVarghese** [comment]
Hey, @wyze Thanks for reviewing and approval. I was wondering when would this be available in npm. Is it possible for us to do a patch release to the latest?

**Comment by wyze** [comment]
Unfortunately, I can't do npm releases yet, so we will have to wait on @plouc to make a release. Hopefully it won't be too long though!

**Comment by SachinVarghese** [comment]
Ok, thanks for your response. In that case, I think the time for the next release would be a question for @plouc. I would also be interested to know if there is a schedule for such releases at regular intervals. Happy to discuss either way. Cheers

**Pull request merged**
