### PR TITLE
Improve with a props to show/hide bar when it's zero

### PR DESCRIPTION
**Pull request by Amitom**
Improvement of https://github.com/plouc/nivo/pull/454, with resolved conflicts (I don't assume the potential next version released with this PR).

I added a prop to decide if zero bar is "shown" or not, by default it's the same behavior than currently.

### CODE REVIEW

**Comment by cookkate** [comment]
We could really use this PR, if #454 isn't tenable.

**Comment by Stephen-ONeil** [comment]
Oh, +1 this, actually

**Comment by Mihier-Roy** [comment]
+1 this. Could we have this released anytime soon?

**Comment by akornmeier** [comment]
This update would be a great addition to the chart component. Would like to see the same ability to show the `0 bar` when the graph is in grouped mode too. That would necessitate a change to the `./compute/grouped.js` file.

**Comment by Blerd** [comment]
+1 would definitely love this out :)

**Comment by justinro-underscore** [comment]
Any updates on this?

**Pull request closed without merging**
